/*

(c) 2016 Copyright Vaclav2016 https://github.com/vaclav2016, jabber id vaclav2016@jabber.cz

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <stdio.h>
#include<stdlib.h>
#include<string.h>
#include"ini.h"

#define XINI_DEBUG

size_t hashCode(char *name) {
	size_t result = 0;
	if(name != NULL) {
		while(*name != 0) {
			result = result * 31 + (*name);
			name++;
		}
	}
	return 0;
}

struct IniValue {
	char *name;
	size_t hcode;
	char *value;
	struct IniValue *next;
};

struct IniSection {
	char *name;
	size_t hcode;
	struct IniValue *value;
	struct IniSection *next;
};

struct IniFile {
	struct IniSection *sections;
	struct IniSection *nosection;
	char error;
};

void ini_free_section(struct IniSection *section);

char *skipSpaces(char *ptr) {
	while((*ptr <= ' ') && (*ptr != '\n') && (*ptr != 0)) {
		ptr++;
	}
	return ptr;
}

char *skipComment(char *ptr) {
	char eol;
	while(*ptr != 0) {
		eol = *ptr=='\n';
		ptr++;
		if(eol) {
			break;
		}
	}
	return ptr;
}

char *createStr(char *begin, char *end) {
	char *r = malloc(end - begin + 1);
	memcpy(r, begin, end-begin);
	r[end-begin] = 0;
	return r;
}

char *parseNewSection(struct IniFile *ini, char *ptr) {
	char *result;
	char *endName;
	ptr = skipSpaces(ptr);
	endName = ptr;
	while((*endName!=0) && (*endName!=']') && (*endName!='\n')) {
		endName++;
	}
	if(*endName!=']') {
#ifdef INI_DEBUG
		printf("error1\n");
#endif
		ini->error = 1;
		return result;
	}
	result = endName + 1;
	endName--;
	while((ptr <= endName) && (*endName<=' ')) {
		endName--;
	}
	if((*endName >= ' ') && (*endName != ']')) {
		endName++;
	}
	if(endName != ptr) {
		struct IniSection *cur = malloc(sizeof(struct IniSection));
		cur->name = createStr(ptr, endName);
		cur->hcode = hashCode(cur->name);
		cur->next = ini->sections;
		cur->value = NULL;
		ini->sections = cur;
	} else {
#ifdef INI_DEBUG
		printf("error2\n");
#endif
		ini->error = 1;
	}
#ifdef INI_DEBUG
	printf("install new section [%s]\n", ini->sections->name);
#endif
	return result;
}

char *parseNewValue(struct IniFile *ini, struct IniSection *section, char *ptr) {
	char *nameBegin = ptr;
	char *nameEnd = ptr;
	char *valueBegin;
	char *valueEnd;
	char *result;

	while((*nameEnd != 0) && (*nameEnd != '=') && (*nameEnd != '\n')) {
		nameEnd++;
	}
	if(*nameEnd != '=') {
#ifdef INI_DEBUG
		printf("error3 at [%s]\n", nameEnd);
#endif
		ini->error = 1;
		return nameEnd;
	}
	valueBegin = nameEnd + 1;
	while((nameEnd >= nameBegin) && (*(nameEnd-1) <= ' ')) {
		nameEnd--;
	}
	valueBegin = skipSpaces(valueBegin);
	if( *valueBegin == 0 ) {
#ifdef INI_DEBUG
		printf("error4\n");
#endif
		ini->error = 1;
		return valueBegin;
	}
	valueEnd = valueBegin;
	while((*valueEnd != 0) && (*valueEnd != '\n')) {
		valueEnd++;
	}
	result = valueEnd;
	while((valueBegin <= valueEnd) && (*valueEnd <= ' ')) {
		valueEnd--;
	}
	if(*valueEnd > ' ') {
		valueEnd++;
	}
	if(valueBegin<valueEnd) {
		struct IniValue *v = malloc(sizeof(struct IniValue));
		v->next = section->value;
		section->value = v;

		v->name = createStr(nameBegin, nameEnd);
		v->hcode = hashCode(v->name);
		v->value = createStr(valueBegin, valueEnd);
#ifdef INI_DEBUG
		printf("install new value [%s] = [%s]\n", v->name, v->value);
#endif
	}
	return result;
}

void *ini_load(char *fname) {
	FILE *f = fopen(fname, "r");
	if( f == NULL) {
#ifdef INI_DEBUG
		printf("cant open\n");
#endif
		return NULL;
	}
	fseek(f, 0L, SEEK_END);
	long fsize = ftell(f);
	fseek(f, 0L, SEEK_SET);
	char *mem = malloc(fsize+1);
	char *ptr = mem;
	int readErr = fread(mem, 1, fsize, f) != fsize;
	fclose(f);
	if(readErr) {
#ifdef INI_DEBUG
		printf("can't read\n");
#endif
		free(mem);
		return NULL;
	}
	mem[fsize] = 0;
	struct IniFile *ini = malloc(sizeof(struct IniFile));
	ini->error = 0;
	ini->sections = NULL;
	ini->nosection = NULL;
	struct IniSection *current = malloc(sizeof(struct IniSection));
	current->name = NULL;
	current->next = NULL;
	current->value = NULL;
	ini->nosection = current;
	while((*ptr != 0) && (!ini->error)) {
		ptr = skipSpaces(ptr);
		if((*ptr != 0) && (*ptr=='#' || *ptr==';')) {
			ptr = skipComment(ptr);
		} else if((*ptr != 0) && (*ptr=='[')) {
			ptr = parseNewSection(ini, ptr + 1);
			current = ini->sections == NULL ? current : ini->sections;
		} else if((*ptr != 0) && (*ptr=='\n')) {
			ptr++;
		} else if(*ptr != 0) {
			ptr = parseNewValue(ini, current, ptr);
		}
	}
	free(mem);
	if(ini->error) {
#ifdef INI_DEBUG
		printf("ERROR!\n");
#endif
		ini_free(ini);
		ini = NULL;
	}
	return ini;
}

void ini_free_section(struct IniSection *section) {
	struct IniValue *this;
	if( section == NULL ) {
		return;
	}
	if(section->name != NULL) {
		free(section->name);
		section->name = NULL;
	}
	while( (this = section->value) != NULL ) {
		section->value = section->value->next;
		if(this->name != NULL) {
			free(this->name);
			this->name = NULL;
		}
		if(this->value != NULL) {
			free(this->value);
			this->value = NULL;
		}
		free(this);
	}
	free(section);
}

void ini_free(void *b) {
	struct IniFile *ini = b;
	struct IniSection *this;
	if( b == NULL ) {
		return;
	}
	while( (this = ini->sections) != NULL ) {
		ini->sections = ini->sections->next;
		ini_free_section(this);
	}
	if(ini->nosection != NULL ) {
		ini_free_section(ini->nosection);
		ini->nosection = NULL;
	}
	free(ini);
}

struct IniValue *lookup_val(struct IniSection *sec, char *name) {
	if(sec == NULL) {
		return NULL;
	}
	size_t hcode = hashCode(name);
	struct IniValue *v = sec->value;
	while(v != NULL) {
		if( hcode ==v->hcode ) {
			if((v->name != NULL) && (strcmp(v->name, name)==0)) {
				return v;
			}
			break;
		}
		v = v->next;
	}
	return v;
}

void ini_getstr(void *iniptr, char *section, char *name, char *value, int len) {
	struct IniFile *ini = iniptr;
	struct IniSection *sec = NULL;
	struct IniValue *val = NULL;
	if(ini == NULL) {
		*value = 0;
		return;
	}
	size_t hcode = hashCode(section);
	sec = ini->sections;
	while( sec != NULL ) {
		if(hcode == sec->hcode) {
			if((sec->name != NULL) && (strcmp(sec->name, section) == 0)) {
#ifdef INI_DEBUG
				printf("section [%s] found\n", section);
#endif
				break;
			}
		}
		sec = sec->next;
	}
	val = lookup_val(sec, name);
	val = (val == NULL) ? lookup_val(ini->nosection, name) : val;
	if( val == NULL ) {
#ifdef INI_DEBUG
		printf("key [%s] not found\n", name);
#endif
		*value = 0;
		return;
	}
	strncpy(value, val->value, len-1);
}

void ini_getint(void *iniptr, char *section, char *name, uint64_t *value) {
	char buf[32];
	int sign = 1;
	int i;
	uint64_t result = 0;
	*value = 0;
	ini_getstr(iniptr, section, name, buf, sizeof(buf));
	i = 0;
	if(buf[i] == '-') {
		sign = -1;
		i++;
	} else if(buf[i] == '+') {
		i++;
	}
	while(buf[i] != 0) {
		if((buf[i] >= '0') && (buf[i] <= '9')) {
			result = result * 10 + (buf[i] - '0');
		} else {
			break;
		}
		i++;
	}
	if(buf[i] == 0) {
		*value = sign*result;
	}
}

void ini_getbool(void *iniptr, char *section, char *name, char *value) {
	char buf[16];
	*value = 0;
	ini_getstr(iniptr, section, name, buf, sizeof(buf));
	if(strcasecmp(buf, "y")==0 || strcasecmp(buf, "yes")==0 || strcasecmp(buf, "true")==0 || strcasecmp(buf, "1")==0 || strcasecmp(buf, "t")==0) {
		*value = 1;
	}
}

#ifdef INI_DEBUG
main() {
	char buf[100];
	void *ini = ini_load("test.conf");
	uint64_t value;
	if(ini == NULL) {
		printf("ini = NULL\n");
	} else {
		ini_getstr(ini, "test", "test_str", buf, sizeof(buf));
		ini_getint(ini, "test", "test_str", &value);
		printf("[%s] = %i\n", buf, (int)value);
		ini_getstr(ini, "test", "b", buf, sizeof(buf));
		printf("[%s]\n", buf);
		ini_free(ini);
	}
}
#endif
